Controllers/CharacterController.cs
using Microsoft.AspNetCore.Mvc;
using CharacterCreator.Models;
using CharacterCreator.Controllers.Utility;
using CharacterCreator.Interfaces;
using System.Security.Claims;

namespace CharacterCreator.Controllers
{
	public class CharacterController : Controller
	{
		public static IDataAccessLayer DAL;
		public CharacterController(IDataAccessLayer dal)
		{
			DAL = dal;
		}

		public IActionResult NewCharacter()
		{
			Character ch = new Character();
			ch.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);

			DAL.addCharacter(ch);
			return EditCharacter(ch);
		}

		[HttpPost]
		public IActionResult EditCharacter(string id)
		{
			Character ch = DAL.getCharacter(int.Parse(id));
			CharacterManager.Load(ch);

			if (ch != null)
			{
				bool got0 = false;
				bool got1 = false;
				bool got2 = false;

				while (!got0)
				{
					TempData["sb1"] = "";
					TempData["sf1"] = "";
					TempData["st1"] = "";
					TempData["si1"] = "";
					TempData["sp1"] = "";
					TempData["sa1"] = "";

					if (ch.brawnAtt == (AttributeScore)1) { TempData["sb1"] = "checked"; got0 = true; break; }
					if (ch.finesseAtt == (AttributeScore)1) { TempData["sf1"] = "checked"; got0 = true; break; }
					if (ch.toughAtt == (AttributeScore)1) { TempData["st1"] = "checked"; got0 = true; break; }
					if (ch.intellectAtt == (AttributeScore)1) { TempData["si1"] = "checked"; got0 = true; break; }
					if (ch.personAtt == (AttributeScore)1) { TempData["sp1"] = "checked"; got0 = true; break; }
					if (ch.acuityAtt == (AttributeScore)1) { TempData["sa1"] = "checked"; got0 = true; break; }
					got0 = true;
				}

				while (!got1)
				{
					if (ch.brawnAtt == (AttributeScore)1 && TempData["sb1"] != "checked") { TempData["sb2"] = "checked"; got1 = true; break; }
					if (ch.finesseAtt == (AttributeScore)1 && TempData["sf1"] != "checked") { TempData["sf2"] = "checked"; got1 = true; break; }
					if (ch.toughAtt == (AttributeScore)1 && TempData["st1"] != "checked") { TempData["st2"] = "checked"; got1 = true; break; }
					if (ch.intellectAtt == (AttributeScore)1 && TempData["si1"] != "checked") { TempData["si2"] = "checked"; got1 = true; break; }
					if (ch.personAtt == (AttributeScore)1 && TempData["sp1"] != "checked") { TempData["sp2"] = "checked"; got1 = true; break; }
					if (ch.acuityAtt == (AttributeScore)1 && TempData["sa1"] != "checked") { TempData["sa2"] = "checked"; got1 = true; break; }
					got1 = true;
				}

				while (!got2)
				{
					if (ch.brawnAtt == (AttributeScore)2) { TempData["wb1"] = "checked"; got2 = true; break; }
					if (ch.finesseAtt == (AttributeScore)2) { TempData["wf1"] = "checked"; got2 = true; break; }
					if (ch.toughAtt == (AttributeScore)2) { TempData["wt1"] = "checked"; got2 = true; break; }
					if (ch.intellectAtt == (AttributeScore)2) { TempData["wi1"] = "checked"; got2 = true; break; }
					if (ch.personAtt == (AttributeScore)2) { TempData["wp1"] = "checked"; got2 = true; break; }
					if (ch.acuityAtt == (AttributeScore)2) { TempData["wa1"] = "checked"; got2 = true; break; }
					got2 = true;
				}
			}

			TempData["sDet"] = "active";
			return View("CharacterCreator", ch);
		}

		public IActionResult DeleteCharacter(string id)
		{
			Character ch = DAL.getCharacter(int.Parse(id));
			if (ch != null) DAL.deleteCharacter(int.Parse(id));

			return RedirectToAction("Characters", "Account");
		}

		public IActionResult EditCharacter(Character ch)
		{
			CharacterManager.Load(ch);
			TempData["sDet"] = "active";
			TempData["sAtt"] = "disabled";
			TempData["sSki"] = "disabled";
			TempData["sInt"] = "disabled";

			if (ch != null)
			{
				bool got0 = false;
				bool got1 = false;
				bool got2 = false;

				while (!got0)
				{
					TempData["sb1"] = "";
					TempData["sf1"] = "";
					TempData["st1"] = "";
					TempData["si1"] = "";
					TempData["sp1"] = "";
					TempData["sa1"] = "";

					if (ch.brawnAtt == (AttributeScore)1) { TempData["sb1"] = "checked"; got0 = true; break; }
					if (ch.finesseAtt == (AttributeScore)1) { TempData["sf1"] = "checked"; got0 = true; break; }
					if (ch.toughAtt == (AttributeScore)1) { TempData["st1"] = "checked"; got0 = true; break; }
					if (ch.intellectAtt == (AttributeScore)1) { TempData["si1"] = "checked"; got0 = true; break; }
					if (ch.personAtt == (AttributeScore)1) { TempData["sp1"] = "checked"; got0 = true; break; }
					if (ch.acuityAtt == (AttributeScore)1) { TempData["sa1"] = "checked"; got0 = true; break; }
					got0 = true;
				}

				while (!got1)
				{
					if (ch.brawnAtt == (AttributeScore)1 && TempData["sb1"] != "checked") { TempData["sb2"] = "checked"; got1 = true; break; }
					if (ch.finesseAtt == (AttributeScore)1 && TempData["sf1"] != "checked") { TempData["sf2"] = "checked"; got1 = true; break; }
					if (ch.toughAtt == (AttributeScore)1 && TempData["st1"] != "checked") { TempData["st2"] = "checked"; got1 = true; break; }
					if (ch.intellectAtt == (AttributeScore)1 && TempData["si1"] != "checked") { TempData["si2"] = "checked"; got1 = true; break; }
					if (ch.personAtt == (AttributeScore)1 && TempData["sp1"] != "checked") { TempData["sp2"] = "checked"; got1 = true; break; }
					if (ch.acuityAtt == (AttributeScore)1 && TempData["sa1"] != "checked") { TempData["sa2"] = "checked"; got1 = true; break; }
					got1 = true;
				}

				while (!got2)
				{
					if (ch.brawnAtt == (AttributeScore)2) { TempData["wb1"] = "checked"; got2 = true; break; }
					if (ch.finesseAtt == (AttributeScore)2) { TempData["wf1"] = "checked"; got2 = true; break; }
					if (ch.toughAtt == (AttributeScore)2) { TempData["wt1"] = "checked"; got2 = true; break; }
					if (ch.intellectAtt == (AttributeScore)2) { TempData["wi1"] = "checked"; got2 = true; break; }
					if (ch.personAtt == (AttributeScore)2) { TempData["wp1"] = "checked"; got2 = true; break; }
					if (ch.acuityAtt == (AttributeScore)2) { TempData["wa1"] = "checked"; got2 = true; break; }
					got2 = true;
				}
			}

			return View("CharacterCreator", ch);
		}

		public IActionResult EditAttributes(string btnradio0, string btnradio1, string btnradio2)
		{
			if (CharacterManager.character != null)
			{
				bool got0 = false;
				bool got1 = false;
				bool got2 = false;

				while (!got0)
				{
					TempData["sb1"] = "";
					TempData["sf1"] = "";
					TempData["st1"] = "";
					TempData["si1"] = "";
					TempData["sp1"] = "";
					TempData["sa1"] = "";

					if (CharacterManager.character.brawnAtt		== (AttributeScore) 1) { TempData["sb1"] = "checked"; got0 = true; break; }
					if (CharacterManager.character.finesseAtt	== (AttributeScore) 1) { TempData["sf1"] = "checked"; got0 = true; break; }
					if (CharacterManager.character.toughAtt		== (AttributeScore) 1) { TempData["st1"] = "checked"; got0 = true; break; }
					if (CharacterManager.character.intellectAtt == (AttributeScore) 1) { TempData["si1"] = "checked"; got0 = true; break; }
					if (CharacterManager.character.personAtt	== (AttributeScore) 1) { TempData["sp1"] = "checked"; got0 = true; break; }
					if (CharacterManager.character.acuityAtt	== (AttributeScore) 1) { TempData["sa1"] = "checked"; got0 = true; break; }
					got0 = true;
				}

				while (!got1)
				{
					if (CharacterManager.character.brawnAtt		== (AttributeScore) 1 && TempData["sb1"] != "checked") { TempData["sb2"] = "checked"; got1 = true; break; }
					if (CharacterManager.character.finesseAtt	== (AttributeScore) 1 && TempData["sf1"] != "checked") { TempData["sf2"] = "checked"; got1 = true; break; }
					if (CharacterManager.character.toughAtt		== (AttributeScore) 1 && TempData["st1"] != "checked") { TempData["st2"] = "checked"; got1 = true; break; }
					if (CharacterManager.character.intellectAtt == (AttributeScore) 1 && TempData["si1"] != "checked") { TempData["si2"] = "checked"; got1 = true; break; }
					if (CharacterManager.character.personAtt	== (AttributeScore) 1 && TempData["sp1"] != "checked") { TempData["sp2"] = "checked"; got1 = true; break; }
					if (CharacterManager.character.acuityAtt	== (AttributeScore) 1 && TempData["sa1"] != "checked") { TempData["sa2"] = "checked"; got1 = true; break; }
					got1 = true;
				}

				while (!got2)
				{
					if (CharacterManager.character.brawnAtt		== (AttributeScore) 2) { TempData["wb1"] = "checked"; got2 = true;  break;}
					if (CharacterManager.character.finesseAtt	== (AttributeScore) 2) { TempData["wf1"] = "checked"; got2 = true;  break;}
					if (CharacterManager.character.toughAtt		== (AttributeScore) 2) { TempData["wt1"] = "checked"; got2 = true;  break;}
					if (CharacterManager.character.intellectAtt == (AttributeScore) 2) { TempData["wi1"] = "checked"; got2 = true;  break;}
					if (CharacterManager.character.personAtt	== (AttributeScore) 2) { TempData["wp1"] = "checked"; got2 = true;  break;}
					if (CharacterManager.character.acuityAtt	== (AttributeScore) 2) { TempData["wa1"] = "checked"; got2 = true; break; }
					got2 = true;
				}
			}

			TempData["sDet"] = "";
			TempData["sAtt"] = "";
			TempData["sSki"] = "disabled";
			TempData["sInt"] = "disabled";

			if (Utilities.AnyNull(new string[] { btnradio2, btnradio1, btnradio0 }))
			{
				TempData["ErrorDisplay"] = "You Must Select Two Strong Attributes and One Weak Attribute";
				TempData["sAtt"] = "active";
				return View("CharacterCreator", CharacterManager.character);
			}

			if (Utilities.AnyEqual(btnradio2, btnradio1, btnradio0))
			{
				TempData["ErrorDisplay"] = "Don't Select The Same Attribute Twice";
				TempData["sAtt"] = "active";
				return View("CharacterCreator", CharacterManager.character);
			}
			else
			{
				CharacterManager.character.brawnAtt = 0;
				CharacterManager.character.finesseAtt = 0;
				CharacterManager.character.toughAtt = 0;
				CharacterManager.character.intellectAtt = 0;
				CharacterManager.character.personAtt = 0;
				CharacterManager.character.acuityAtt = 0;

				switch (btnradio0)
				{
					case "Brawn": CharacterManager.character.brawnAtt = (AttributeScore)1; break;

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CharacterCreator.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Character Creator Website</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_ViewCharactersPartial" />
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Profiles">Profiles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="CreateProfile">Profile Creator</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2023 - Originated by 505 - Licensed Under F*ck Around and Find Out (FAFO) v0.2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ViewCharactersPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
<li class="nav-item">
    <a class="nav-link" asp-area="" asp-controller="Character" asp-action="NewCharacter">New Character</a>
</li>
<li class="nav-item">
    <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Characters">My Characters</a>
</li>
}